
//----------------------------------------------------
// The following code was generated by CUP v0.11joho 20081107
// Sat Nov 08 22:01:27 CET 2008
//----------------------------------------------------

package java_cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public final int RBRACK = 26;
  public final int PACKAGE = 2;
  public final int LT = 29;
  public final int LBRACK = 25;
  public final int STAR = 15;
  public final int NON = 8;
  public final int TERMINAL = 7;
  public final int CODE_STRING = 34;
  public final int PERCENT_PREC = 24;
  public final int RIGHT = 22;
  public final int ID = 33;
  public final int EOF = 0;
  public final int SEMI = 13;
  public final int ACTION = 5;
  public final int CODE = 4;
  public final int COLON = 17;
  public final int COLON_COLON_EQUALS = 18;
  public final int NONTERMINAL = 27;
  public final int IMPORT = 3;
  public final int error = 1;
  public final int NONASSOC = 23;
  public final int QUESTION = 30;
  public final int COMMA = 14;
  public final int LEFT = 21;
  public final int SCAN = 10;
  public final int GT = 28;
  public final int START = 12;
  public final int SUPER = 31;
  public final int DOT = 16;
  public final int EXTENDS = 32;
  public final int INIT = 9;
  public final int PARSER = 6;
  public final int PRECEDENCE = 20;
  public final int BAR = 19;
  public final int WITH = 11;
}

